api/urls.py
from django.urls import path

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

from api.views import (
    StudentProfileViewSet,
    CourseViewSet,
    StudentCourseRegistrationViewSet,
    MonthCourseCalendarView,
)

app_name = 'api'
router = DefaultRouter(trailing_slash=False)

urlpatterns = [
    path('get_auth_token', obtain_auth_token),
    path('calendar', MonthCourseCalendarView.as_view(), name='api_calendar')
]

router.register('students', StudentProfileViewSet, basename='api_users')
router.register('courses', CourseViewSet, basename='api_courses')
router.register('registration', StudentCourseRegistrationViewSet, basename='api_registration')
urlpatterns += router.urls

main_page/urls.py
from django.urls import path

from main_page import views

app_name = 'main_page'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('courses_list/', views.courses_list, name='courses_list'),
    path('course_detail/<int:pk>', views.course_detail, name='course_detail'),
    path('course_register/<int:course_id>/<int:student_id>', views.course_register, name='course_register'),
    path('cancel_course_registration/<int:course_id>/<int:student_id>',
         views.cancel_course_registration, name='cancel_course_registration'
         ),
    path('calendar/', views.courses_calendar, name='courses_calendar'),
    path('start_email_scheduler/', views.admin_start_email_scheduler, name='start_email_scheduler'),
]

otus_final_project/urls.py
from django.contrib import admin
from django.urls import path, include

from .settings import DEBUG

import main_page.urls
from main_page.views import index_view
import api.urls

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index_view, name='index'),
    path('index/', index_view, name='index'),
    path('learn/', include(main_page.urls)),
    path('api/v1/', include(api.urls), name='api'),
]

if DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += [
    path('django-rq/', include('django_rq.urls'))
]

templates/dj/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Learn To Fly</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <script type="text/javascript" src="/static/js/latin_proverbs.js"></script>
</head>
<body>
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mr-auto">
    <a class="navbar-brand" href="{% url 'admin:index' %}">
        <img src="{% static 'images/dj.png' %}" width="30" height="30" alt="brand">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if active == 'home' %}
                <a class="nav-item nav-link active" href="{% url 'index' %}">Home</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="#">Logged: {{ user.username }}</a>
                <a class="nav-item nav-link" href="{% url 'main_page:user_logout' %}">Logout</a>
                <a class="nav-item nav-link" href="{% url 'main_page:courses_list' %}">Courses List</a>
                <a class="nav-item nav-link" href="{% url 'main_page:courses_calendar' %}">Calendar</a>
            {% else %}
                {% if active == 'register' %}
                    <a class="nav-item nav-link active" href="{% url 'main_page:user_register' %}">Register</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'main_page:user_register' %}">Register</a>
                {% endif %}
                {% if active == 'login' %}
                    <a class="nav-item nav-link active" href="{% url 'main_page:user_login' %}">Login</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'main_page:user_login' %}">Login</a>
                {% endif %}
            {% endif %}
        </div>
            <a class="navbar-text mx-auto phrase">Phrase of the day</a>
    </div>
    <span class="navbar-text right">Django Demo Site - Otus's Web Developer 2019 course</span>
</nav>

<div class="jumbotron jumbotron-fluid">
    {% block body_block %}
    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="/static/js/base_navbar_animation.js"></script>
</body>
</html>

templates/dj/calendar.html
{% extends 'dj/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <div class="alert alert-dark text-center" role="alert">
        <h2>Calendar page</h2>
    </div>

    <div class="container-fluid col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <form id="calendar_form" class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-inline">

                <label for="month"></label>
                <div class="col-auto mb-2">
                    <select class="form-control custom-select mr-sm-2" name="month" id="month">
                        {% for m in all_months %}
                            {% if m == month %}
                                <option selected value="{{ m }}">{{ m }}</option>
                            {% else %}
                                <option value="{{ m }}">{{ m }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <label for="year"></label>
                <div class="col-auto mb-2">
                    <select class="form-control custom-select mr-sm-2" name="year" id="year">
                        {% for y in all_years %}
                            {% if y == year %}
                                <option selected value="{{ y }}">{{ y }}</option>
                            {% else %}
                                <option value="{{ y }}">{{ y }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="col-auto mb-2">
                    <button type="submit" class="btn btn-primary">Show Calendar</button>
                </div>

            </div>
        </form>
    </div>

    <div class="container col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <ul class="list-group">
            {% if courses %}
                {% for course in courses %}
                    <li class="list-group-item list-group-item-action">
                        <a href="/learn/course_detail/{{ course.id }}">
                            <em> {{ course.start_date }}&emsp;</em>
                            <em>{{ course.title }}&emsp;&emsp;</em>
                            <em>{{ course.student_registered }}&emsp;</em>
                        </a>
                    </li>
                {% endfor %}
            {% else %}
                <em>No scheduled courses yet!</em>
            {% endif %}

        </ul>
    </div>

{% endblock %}

templates/dj/course_detail.html
{% extends 'dj/base.html' %}
{% load staticfiles %}

{% block body_block %}

    <div class="alert alert-dark text-center" role="alert">
        <h2>Detailed Course Description</h2>
    </div>

    <div class="container col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

        <h3>Title: <em>{{ course.title }}</em></h3>
        <h3>Price: {{ course.price }}$ </h3>
        <h2>Summary:</h2>
        <h5>{{ course.description|safe }} </h5>

        {% if lectures %}
            <h2>Lectures:</h2>
            {% for lecture in lectures %}
                <li># {{ lecture.number_in_course }}  <em>{{ lecture.title }}</em>
            {% endfor %}
        {% else %}
            <li><em>No lectures added yet!</em>
        {% endif %}
        {% if registrations %}
            <h2>Registered: {{ registrations }} students</h2>
        {% else %}
            <li><em>No lectures added yet!</em>
        {% endif %}
        {% if scheduled %}
            <h2>Course will start: {{ scheduled }}</h2>
            {% if student %}
                {% if student_registered %}
                    <a class="nav-item nav-link"
                       href="{% url 'main_page:cancel_course_registration' course.id student.id %}">
                        <h2>Cancel registration</h2>
                    </a>
                {% else %}
                    <a class="nav-item nav-link"
                       href="{% url 'main_page:course_register' course.id student.id %}">
                        <h2>Register to this course</h2>
                    </a>
                {% endif %}
            {% endif %}
        {% else %}
            <div><em>Course is not scheduled yet!</em></div>
        {% endif %}
    </div>
{% endblock %}

templates/dj/course_registration.html
{% extends 'dj/base.html' %}
{% load staticfiles %}

{% block body_block %}

    {% if student_registered %}
        <div class="alert alert-success text-center" role="alert">
            You are registered for this course!
        </div>
    {% elif errors %}
        <div class="alert alert-danger text-center" role="alert">
            {{ errors }}
        </div>
    {% else %}
        <div class="alert alert-dark text-center" role="alert">
            Course Registration page
        </div>
        <div class="container col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info">
                <div class="panel-body">
                    <form id="signupform" class="form-horizontal" role="form" method="POST"
                          enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="course" class="col-md-3 control-label">Course</label>
                            <div class="col-md-9">
                                {{ course_registration_form.course }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="student" class="col-md-3 control-label">Student</label>
                            <div class="col-md-9">
                                {{ course_registration_form.student }}
                            </div>
                        </div>

                        <div class="form-group">
                            <!-- Button -->
                            <div class="col-md-offset-3 col-md-9">
                                <button id="btn-signup" type="submit" class="btn btn-info"><i
                                        class="icon-hand-right"></i>
                                    &nbsp Register
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

templates/dj/courses_list.html
{% extends 'dj/base.html' %}
{% load staticfiles %}

{% block body_block %}

    <div class="alert alert-dark text-center" role="alert">
        <h2>Courses List</h2>
    </div>

    <div class="container col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <ul class="list-group">
            {% if courses %}
                {% for course in courses %}
                    <li class="list-group-item list-group-item-action">
                        <a href="/learn/course_detail/{{ course.id }}">
                            ID: <em>{{ course.id }}&emsp;</em>
                            Title: <em>{{ course.title }}&emsp;</em>
                            Price: <em>{{ course.price }}$&emsp;</em>
                        </a>
                        {% if student_id and course.id in student_registrations %}
                            &emsp;(you are registered)
                        {% endif %}
                    </li>
                {% endfor %}
            {% else %}
                <em>No courses in the DB!</em>
            {% endif %}
        </ul>
    </div>
{% endblock %}

templates/dj/extra_admin.html
{#{% extends "admin/index.html" %}#}
{% extends "django_rq/index.html" %}

{% block extrastyle %}
    {{ block.super }}
    <style>#extra_func table {width: 100%;}</style>
{% endblock %}

{% block sidebar %}
    {{ block.super }}
    <div id="extra_func">
        <div class="module">
            <table>
                <caption>Additional Services</caption>
                <tbody>
                    <tr>
                        <th>
                            <a href = "{% url 'main_page:start_email_scheduler' %}">Start Email Scheduler</a>
                        </th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/dj/index.html
{% extends 'dj/base.html' %}
{% load staticfiles %}

{% block body_block %}

    <div class="alert alert-dark text-center" role="alert">
        <h2>Main page</h2>
    </div>

    <div class="media text-center">
        <img src="{% static 'images/dog_surprize.jpg' %}" class="img-fluid mx-auto d-block"
             alt="Responsive image">
    </div>

{% endblock %}

templates/dj/login.html
{% extends 'dj/base.html' %}
{% load staticfiles %}

{% block body_block %}

    {% if errors %}
        <div class="alert alert-danger text-center" role="alert">
            {{ errors }}
        </div>
    {% else %}
        <div class="alert alert-warning text-center" role="alert">
            Login page
        </div>
        <form class="form-inline justify-content-center" action="{% url 'main_page:user_login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group mb-2">
                <label for="username">Username:&nbsp</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Username">
            </div>
            <div class="form-group mx-sm-3 mb-2">
                <label for=password">Password:&nbsp</label>
                <input type="password" class="form-control" id=password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    {% endif %}

{% endblock %}

templates/dj/registration.html
{% extends 'dj/base.html' %}
{% load staticfiles %}

{% block body_block %}

    {% if registered %}
        <div class="alert alert-success text-center" role="alert">
            You are registered, login to access site!
        </div>
    {% elif errors %}
        <div class="alert alert-danger text-center" role="alert">
            {{ errors }}
        </div>
    {% else %}
        <div class="alert alert-dark text-center" role="alert">
            <h2>Registration form</h2>
        </div>

        <div class="container col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info">
                <div class="panel-body">

                    <form id="signupform" class="form-horizontal" role="form" method="POST"
                          enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="username" class="col-md-3 control-label">Username</label>
                            <div class="col-md-9">
                                <input id="id_username" type="text" class="form-control" name="username"
                                       placeholder="User Name" value="{{ username }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password" class="col-md-3 control-label">Password</label>
                            <div class="col-md-9">
                                <input type="password" class="form-control" name="password" value="{{ password }}"
                                       placeholder="Password">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="email" class="col-md-3 control-label">Email</label>
                            <div class="col-md-9">
                                <input type="text" class="form-control" name="email" value="{{ email }}"
                                       placeholder="Email Address">
                            </div>
                        </div>

                        <div class="form-group">
                            <!-- Button -->
                            <div class="col-md-offset-3 col-md-9">
                                <button id="btn-signup" type="submit" class="btn btn-info"><i
                                        class="icon-hand-right"></i>
                                    &nbsp Sign Up
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

templates/dj/start_mail_scheduler.html
{% extends "admin/base_site.html" %}

{% block title %}Email Scheduler {{ block.super }}{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <style>table {
        width: 100%;
    }</style>
{% endblock %}

{% block content_title %}<h1>Start Email Scheduler</h1>{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">Home</a> &rsaquo;
        <a href="{% url 'main_page:start_email_scheduler' %}">Email Scheduler</a>
    </div>
{% endblock %}

{% block content %}

    <div id="content-main">
        <div class="module">

            <table>
                <thead>
                <tr>
                    <th>Scheduler Name</th>
                    <th>Queue Name</th>
                    <th>Result TTL</th>
                    <th>Interval in secs</th>
                    <th>Repeat Times</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                <th>
                    <a href="#">
                        {{ scheduler_name }}
                    </a>
                </th>
                <th>
                    <a href="#">
                        {{ queue_name }}
                    </a>
                </th>
                <th>
                    <a href="#">
                        {{ result_ttl }}
                    </a>
                </th>
                <th>
                    <a href="#">
                        {{ interval }}
                    </a>
                </th>
                <th>
                    <a href="#">
                        {{ repeat }}
                    </a>
                </th>
                <th>
                    <a href="#">
                        {{ status }}
                    </a>
                </th>
                </tbody>
            </table>

        <form action="" method="post">
            {% csrf_token %}
            <div>
                <input type="submit" value="Start Email Scheduler" />
            </div>
        </form>


        </div>
    </div>

{% endblock %}